### ISSUE TITLE
严重bug: 首页的中央1，右下角显示是蓝光(1080p)，但实际绝不是1080p，清晰度比央视网的720p还要差！

### ISSUE THREAD

**Issue by zbby1987** [matrix3d/CCTV_Viewer#11]
这是怎么回事！？
难道需要我手动从新点一下  清晰度选项？

应该用js强制指定到1080p吧

**Comment by matrix3d** [comment]
清晰度是根据网速自动决定的

**Comment by zbby1987** [comment]
> 清晰度是根据网速自动决定的

可以用js去强制指定分辨率的吧，
CCTV1-1080p
CCTV1-  720p
两个台也行
